"""Add stripe_payment_intent_id

Revision ID: b52ee5b5f7fe
Revises: 3b20dfd59ea7
Create Date: 2026-06-15 11:26:56.198645

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'b52ee5b5f7fe'
down_revision: Union[str, Sequence[str], None] = '3b20dfd59ea7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment', sa.Column('stripe_payment_intent_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payment', 'stripe_payment_intent_id')
    # ### end Alembic commands ###
